### ISSUE TITLE
Unable to generate titleIndexes dynamically

### ISSUE THREAD

**Issue by bala-techguy** [TreeFarmer/embed-table#4]
First of all thanks for the wonderful tool. I'm trying to make use of this. 

In my case, `titleIndexes` will have to be dynamically populated based on the max length of the data. I was able to successfully make `columnIndexes` dynamic but it is not adjusting well with the `titleIndexes`. Please refer to the below screenshot. 

![image](https://user-images.githubusercontent.com/23168216/202897110-98a2fb0b-494e-409b-88c2-433bce276ec8.png)

Hope you can understand what I mean from the screenshot.

**Comment by ExtremeStylez** [comment]
Bro mine says invalid Count can u help me out??

**Comment by bala-techguy** [comment]
> Bro mine says invalid Count can u help me out??

Invalid count is totally a different issue and a generic error. Check if all the 3 arrays have the right number of elements.

**Comment by Fyrlex** [comment]
Hi there,

Thank you so much for reaching out! 

What it seems to be is that columns can be dynamically updated because the characters inside ticks (`) are all equal width, but the titles cannot be monospaced with the ticks due to the way Discord programmed that text area. I assume you're able to make it dynamic but it's not accurate, correct?

This issue could be resolved by adding a new way to make a table without using an EmbedField and instead using the description part of the Embed.

**Comment by bala-techguy** [comment]
Thanks for the reply. 

Yes, I'm able to make it dynamic but not sure how to plan the spacing. 

Yes, I was also thinking the same. The characters inside ticks are regular but the title is not like that. I even thought of bringing the Title inside the tick and having a line below (with hyphens) to differentiate it and leave the title altogether but not sure if the title is mandatory. But that can be a good workaround I guess.

**Comment by Fyrlex** [comment]
Hey!

I was able to add a new method to the Table class, allowing you to easily convert it to a string. In your case, just use `Table.toString()` inside the embed description.

Install the latest version and let me know how it goes.
